# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

imports:
    - { resource: '../src/Shared/config/services.yaml' }
    - { resource: '../src/Security/config/services.yaml' }
    - { resource: '../src/Auth/config/services.yaml' }
    - { resource: '../src/User/config/services.yaml' }
    - { resource: '../src/Task/config/services.yaml' }
    - { resource: '../src/Project/config/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
