api_platform:
    defaults:
        stateless: true

    mapping:
        paths:
            - '%kernel.project_dir%/src/User/Infrastructure/ApiPlatform/Resource'
            - '%kernel.project_dir%/src/Task/Infrastructure/ApiPlatform/Resource'
            - '%kernel.project_dir%/src/Project/Infrastructure/ApiPlatform/Resource'
