services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\:
        resource: '../'

    App\Shared\Infrastructure\Mapper\MappingConfigLoader:
        arguments:
            $configDirs:
                - '%kernel.project_dir%/src/User/Infrastructure/ApiPlatform/Config'
                - '%kernel.project_dir%/src/Task/Infrastructure/ApiPlatform/Config'
